remote_theme: pmarsceill/just-the-docs
title: OpenAPI Documentation
description: For API designers and writers wishing formalize their API in an OpenAPI Description document.
baseurl: /Documentation
logo: "/assets/images/OpenAPI_Logo_Pantone-1.png"
footer_content: "&copy; 2020 OpenAPI Initiative. &lt;a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\"&gt;&lt;img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by/4.0/80x15.png\" /&gt;&lt;/a&gt;&lt;br /&gt;This work is licensed under a &lt;a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\"&gt;Creative Commons Attribution 4.0 International License&lt;/a&gt;. The documentation is maintained in &lt;a href="https://github.com/OAI/Documentation/\"&gt;https://github.com/OAI/Documentation/&lt;/a&gt;."
color_scheme: oai
highlighter: rouge
plugins:
  - jekyll-sitemap